# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 3.0.0-preview8-013656
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    sourceFolder: RadTextureViewer.Setup/bin/x64/Release
    contents: '*.msi'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: GitHubRelease@0
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')
  inputs:
    gitHubConnection: nemurimasu
    repositoryName: nemurimasu/RadTextureViewer
    assets: $(Build.ArtifactStagingDirectory)/*
    isDraft: true
    addChangeLog: true
